local String = require 'toolbox.core.string'


describe('String', function()
  describe('.is(x)', function()
    it('should return true if x is a string', function()
      assert.True(String.is("1"))
      assert.True(String.is("a number"))
      assert.True(String.is(""))
      assert.True(String.is("  "))
    end)
    it('should return false if x is not a number', function()
      assert.False(String.is(true))
      assert.False(String.is(false))
      assert.False(String.is({ 1, 2, 3 }))
      assert.False(String.is({ a = 1, b = 2, c = 3 }))
      assert.False(String.is(nil))
      assert.False(String.is(1))
      assert.False(String.is(0))
      assert.False(String.is(-3))
      assert.False(String.is(82.421))
      assert.False(String.is(-3.145))
      assert.False(String.is(1.71e-5))
      assert.False(String.is(3.51E-7))
      assert.False(String.is(0x1F4))
    end)
  end)

  describe('.capitalize(str)', function()
    it('should capitalize the string regardless of capitalization', function()

    end)
  end)
end)
